### ISSUE TITLE
main.go:221: error loading provider plugin 'smtp.prov': plugin: not implemented

### ISSUE THREAD

**Issue by Zuckonit** [knadh/otpgateway#11]
```
main.go:221: error loading provider plugin 'smtp.prov': plugin: not implemented
```
meet some error during my try

**Comment by Zuckonit** [comment]
fix by build from the src. problem only exist at release version(MacOS)

**Comment by ramsrisantosh2712** [comment]
Hi [Zuckonit](https://github.com/Zuckonit),
Could you please share the commands how to run this app locally?
