### ISSUE TITLE
Guide from Installation To Usage

### ISSUE THREAD

**Issue by chsanto2712** [knadh/otpgateway#41]
Respected @knadh @mr-karan sir's,
Thanks a lot for making such amazing projects 😍,
I am new to integrate open source projects to ReactJs applications. But I need to use this functionalities of OTPGATEWAY for verifying Email and Phone number. I am eagerly waiting to integrate OTP verification 😅😜.

So I request you to please share your valuable information to use and integrate them. 🙏

Thank You sir

**Comment by mr-karan** [comment]
All the required information is documented here: https://github.com/knadh/otpgateway#javascript-plugin. Please ask any specific query/issues while integration. 

Thanks!

**Comment by chsanto2712** [comment]
Respected @knadh @mr-karan sir's,
Now I was able to configure REDIS-SERVER and able to run the port 9000(otpgateway) as shown below

<details><summary><b>WORKING REDIS-SERVER 🥳</b></summary>
<p>

![Redis](https://github.com/knadh/otpgateway/assets/92885371/62bfce66-d3c5-477d-818d-c3dd6005bb40)

</p>
</details> 

<details><summary><b>WORKING LOCALHOST:9000 🥳</b></summary>
<p>

![Localhost Terminal](https://github.com/knadh/otpgateway/assets/92885371/05966ee8-d18d-4bc3-81ac-aed81f390df4)

![Localhost:9000](https://github.com/knadh/otpgateway/assets/92885371/2931407e-ed20-442c-98d0-e0587d7365d4)

</p>
</details> 


<details><summary><b>CONFIG.toml file</b></summary>
<p>

![CONFIG file](https://github.com/knadh/otpgateway/assets/92885371/5ce24186-e6e7-4725-824f-267dfc961063)

</p>
</details> 


<b>But the problem was in the fetching the requests</b>

[Want to reproduce this](https://github.com/knadh/otpgateway?tab=readme-ov-file#list-providers)


![GET REQUEST](https://github.com/knadh/otpgateway/assets/92885371/39dfaeb0-0ee6-4bb0-a435-40a6ef4404ff)


Please help me with this issue @mr-karan @knadh sir !.

**Comment by mr-karan** [comment]
The `username` and `password` keys are under the provider settings (like SMTP etc). For API's authentication, it's provided here:

```
# Namespaces (application tenants) and tokens. OTPs are generated
# under these namespaces and the OTP APIs require
# namespace + secret as BasicAuth headers for authentication.
[auth.MyApp]
namespace = "MyApp"
secret = "mySecretToken"
```
